---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: .woven/
      - id: end-of-file-fixer
        exclude: ^(.woven|src/test/resources/stepsDocs)/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional@16.2.1"]

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|ts|js|json)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.47.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.57.0
          - "@typescript-eslint/parser@5.59.8"
          - "@typescript-eslint/eslint-plugin@5.59.8"
        files: \.[jt]sx?$
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.0
    hooks:
      - id: markdownlint
        args: [--config, ".markdownlint.yaml", "--ignore", "README.md"]

  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.5.3
    hooks:
      - id: gitleaks

  # Verify versioning sync
  - repo: local
    hooks:
      - id: sync-package-version
        name: Sync package version
        language: system
        entry: bash -c './scripts/compare-versions.sh'
        pass_filenames: false
